### ISSUE TITLE
Data prep; parse validation data issue.

### ISSUE THREAD

**Issue by kla240** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#1]
Hello, when trying to prepare the dataset, I run into an issue in that the function to write json formatted data is not defined in the open_image_to_json module. 

AttributeError: module 'open_images.open_image_to_json' has no attribute 'write_json_data'

**Comment by jin-nvidia** [comment]
Could you try to change `oij.write_json_data(cocodata, output_json)` to `write_json(cocodata, output_json)` where `write_json` is already imported?

**Comment by kla240** [comment]
yes, that worked...  Just thought it should be updated in the readme... last line of that block.  :)

**Comment by james-nvidia** [comment]
Thank you for brining this to our attention. We will correct it soon.
Please let us know if you use or extend this repo. Thanks!

**Comment by james-nvidia** [comment]
Solved with update https://github.com/NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream/commit/c564b2e078c03bcf912a442546611a7cc486bdda
