### ISSUE TITLE
ERROR 403: Forbidden for downloading "train-annotations-bbox.csv" from "https://datasets.figure-eight.com/figure_eight_datasets/open-images"

### ISSUE THREAD

**Issue by samaujs** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#11]
Hi,

  I have managed to download all files with the following :

except the following file : 

wget https://datasets.figure-eight.com/figure_eight_datasets/open-images/train-annotations-bbox.csv

with the following error : 
--
--2020-12-04 09:11:53--  https://datasets.figure-eight.com/figure_eight_datasets/open-images/train-annotations-bbox.csv
Resolving datasets.figure-eight.com (datasets.figure-eight.com)... 18.205.33.196, 54.87.126.182
Connecting to datasets.figure-eight.com (datasets.figure-eight.com)|18.205.33.196|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://datasets.appen.com/figure_eight_datasets/open-images/train-annotations-bbox.csv [following]
--2020-12-04 09:11:54--  https://datasets.appen.com/figure_eight_datasets/open-images/train-annotations-bbox.csv
Resolving datasets.appen.com (datasets.appen.com)... 3.222.70.108, 3.219.189.222, 18.206.2.100, ...
Connecting to datasets.appen.com (datasets.appen.com)|3.222.70.108|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-12-04 09:11:56 ERROR 403: Forbidden.
--

Is it alright to use the replace the file with "oidv6-train-annotations-bbox.csv" downloaded from "https://appen.com/datasets/open-images-annotated-with-bounding-boxes/".  Thanks.

**Comment by james-nvidia** [comment]
You need a consistent dataset in the right format. I haven't looked at the file you are downloading, but you should make sure that the annotations and the images come from the same version of open images.
I suggest downloading them from the main website here: https://storage.googleapis.com/openimages/web/download.html
