### ISSUE TITLE
Where to download the "processed_train/train_faces.json"?

### ISSUE THREAD

**Issue by samaujs** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#12]
Hi,
  in the plotting for some ground truth, may I know where can "processed_train/train_faces.json" be downloaded for the snippet codes below : 

from data_tools.plot_images import draw_boxes
image_dir = '/data/open_images/train_faces'
anns = '/data/open_images/processed_train/train_faces.json'
output_dir = '/data/open_images/gt_plot_train_faces'
draw_boxes(image_dir, output_dir, anns)
--

**Comment by james-nvidia** [comment]
`train_faces.json` is the annotation file that accompanies the `train_faces` dataset. You need to:

1. Download the open images dataset.
2. Extract just the faces
3. Split into train and val

This repo contains code for all of these stages, but this code has not been maintained, so will require some tweaking to work.
