### ISSUE TITLE
Questions about fps

### ISSUE THREAD

**Issue by jzx-gooner** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#13]
I deploy yolov3 on jetson xavier nx
0)The camera input 25fps
1)set [source]drop-frame-interval=3,so we i get 8fps 
2)set[primary-gie] interval=8,so the pipeline only infer 1fps
3)the other 7fps detect by tracker
4)and the perf is 8fps = deep model infer + detection tracker

Is it right?
thank you very much!

**Comment by james-nvidia** [comment]
That sounds like a very slow inference. What size is your input video? Try reducing it -- the model should still perform well on 360 x 240, for example.
