### ISSUE TITLE
no kernel image is available error on Nano

### ISSUE THREAD

**Issue by kla240** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#3]
I get this error now:

```
root@nano01av4028:~/deepstream_sdk_v4.0.2_jetson/sources/apps/retinanet_for_redaction_with_deepstream# ./deepstream-redaction-app -c configs/nano_file.txt 
Creating LL OSD context new
gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream-4.0/lib/libnvds_mot_klt.so
gstnvtracker: Optional NvMOT_RemoveStreams not implemented
gstnvtracker: Batch processing is OFF


Runtime commands:
	h: Print this help
	q: Quit

	p: Pause
	r: Resume

NOTE: To expand a source in the 2D tiled display and view object details, left-click on the source.
      To go back to the tiled display, right-click anywhere on the window.

** INFO: <bus_callback:163>: Pipeline ready

Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
** INFO: <bus_callback:149>: Pipeline running

Creating LL OSD context new
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: no kernel image is available for execution on the device
Aborted (core dumped)
````

...this is inside the Deepstream4.0.2 container that I've managed to bastardize to get all the dependencies in place for the "export" module in retinanet to compile and run and convert from sm_70 to sm_53 ONNX file.   

this with an mp4 'source' file in the config.   the csi camera doesn't work because nvargus server isn't available within the docker.

**Comment by james-nvidia** [comment]
I have run this repo on a Nano, but I warn you that it has a very low frame rate. We are working on a more efficient backbone that will run more quickly.
This looks like a DeepStream error. Can you successfully run the DeepStream samples?
How did you install DeepStream? You should install it onto the Nano when you flash it.

**Comment by kla240** [comment]
Thanks.   I used the deepstream-l4t:4.0.2-19.12-samples container as a base, and then installed your repo in there and followed your instructions.   I was finally able to get it to work. 

The frame rate is indeed much lower than I was expecting.   Perhaps a mobilenet based model would speed it up considerably.   ResNet18 based model was 1 frame / second.   skipping frames obviously sped it up, but is less robust.

**Comment by james-nvidia** [comment]
While we are working on backbones, you might also try training the model on much smaller images (eg 320 x 240). This should give a much higher frame rate, but at the expense of accuracy when people are further away from the camera. Is that something you could try?

**Comment by egamor18** [comment]
i am having the exact same problem. I am running on Jetson TX2, Deepstream-4.0. I am able to run the sample:
_deepstream-app -c <path to deepstream>/configs/deepstream-app/source4_1080p_dec_infer-resnet_tracker_sgie_tiled_display_int8.txt_  
But the retinanet which I compiled using
_https://devblogs.nvidia.com/real-time-redaction-app-nvidia-deepstream-part-2-deployment/_
does not work. Any help?
