### ISSUE TITLE
NameError: name 'write_json_data' is not defined

### ISSUE THREAD

**Issue by ticlazau** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#4]
Hello,

Following the instructions, when running:

```python
images_dir = '/data/open_images/validation'
annotation_csv = '/data/open_images/validation-annotations-bbox.csv'
category_csv = '/data/open_images/class-descriptions-boxable.csv'
output_json = '/data/open_images/val_faces.json'

# Now we read the Open Images categories and parse our data.

import open_images.open_image_to_json as oij
from data_tools.coco_tools import write_json
catmid2name = oij.read_catMIDtoname(category_csv)
oidata = oij.parse_open_images(annotation_csv) # This is a representation of our dataset.

# We only want images that contain the 'Human Face' class, so we run a function that removes all other images.

set1 = oij.reduce_data(oidata, catmid2name, keep_classes=['Human face'])

# Finally we convert this data to COCO format, using this as an opportunity to exclude any annotations
# that are smaller than 2 x 2 when the input images are resized to maxdim 640, and save to a file.

cocodata = oij.openimages2coco(set1, catmid2name, images_dir,
                               desc="Open Image validation data, set 1.",
                               output_class_ids={'Human face': 1},
                               max_size=880, min_ann_size=(1,1),
                               min_ratio=2.0)
write_json_data(cocodata, output_json)

```

 I am **getting this error**:

 Reducing the dataset. Initial dataset has length 303980
 Reducing the dataset. Final dataset has length 63349
Traceback (most recent call last):
  File "test-data.py", line 25, in <module>
    write_json_data(cocodata, output_json)
**NameError: name 'write_json_data' is not defined**

Is something I am missing? 

Thx,
FM

**Comment by jin-nvidia** [comment]
Hello, thanks for bringing this issue to our attention. Replacing "write_json_data" with "write_json" should work.

**Comment by ticlazau** [comment]
Thanks @jin-nvidia , all good now.

**Comment by ticlazau** [comment]
I believe there is the same issue when parsing training data: 

```python
import open_images.open_image_to_json as oij

# Definine paths
images_dir = ['/data/open_images/train_0%i'%oo for oo in range(9)] # There are nine image directories.
annotation_csv = '/data/open_images/train-annotations-bbox.csv'
category_csv = '/data/open_images/class-descriptions-boxable.csv'
output_json = '/data/open_images/train_faces.json'

# Read the category names
catmid2name = oij.read_catMIDtoname(category_csv)
# Parse the annotations
oidata = oij.parse_open_images(annotation_csv)

# Keep only human faces
trainset1 = oij.reduce_data(oidata, catmid2name, keep_classes=['Human face'])
cocodata = oij.openimages2coco(trainset1, catmid2name, images_dir, desc="Open Image train data, set 1.",
                               output_class_ids={'Human face': 1},
                               max_size=880, min_ann_size=(1,1),
                               min_ratio=2.0)
write_json_data(cocodata, output_json)

```

Making the change you recommend is not working in this case, here is the output:

 Read 601 rows from category csv /nobackup/projects/tmp/open_images/class-descriptions-boxable.csv
 Read 14610229 rows from annotation csv /nobackup/projects/tmp/open_images/train-annotations-bbox.csv
 Reducing the dataset. Initial dataset has length 14610229
 Reducing the dataset. Final dataset has length 4178801

Traceback (most recent call last):
  File "training-data.py", line 20, in <module>
    write_json(cocodata, output_json)
**NameError: name 'write_json' is not defined**

and:

 Read 601 rows from category csv /nobackup/projects/tmp/open_images/class-descriptions-boxable.csv
 Read 14610229 rows from annotation csv /nobackup/projects/tmp/open_images/train-annotations-bbox.csv
 Reducing the dataset. Initial dataset has length 14610229
 Reducing the dataset. Final dataset has length 4178801
Traceback (most recent call last):
  File "training-data.py", line 20, in <module>
    write_json_data(cocodata, output_json)
**NameError: name 'write_json_data' is not defined**
