### ISSUE TITLE
Error Running Container

### ISSUE THREAD

**Issue by corymast** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#8]
After trying to run the container with the following command:

`docker run -it --gpus all --rm --ipc=host -v $DATA_DIR:/data -v $WORKING_DIR:/src -w /src nvcr.io/nvidia/pytorch:19.09-py3`

I receive an error:

> Digest: sha256:51c22009e3c3183cc4b023dc004c5d1ea12243c64a78e08063d0124f9c120683
Status: Downloaded newer image for nvcr.io/nvidia/pytorch:19.09-py3
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

I have logged into nvcr.io and have even tried the nvcr.io/nvidia/pytorch:20.02-py3 container and received the same result.

Any help you can provide is greatly appreciated.

Thanks!

-Cory

**Comment by james-nvidia** [comment]
Hello Cory. Do you have Nvidia-docker installed?
https://github.com/NVIDIA/nvidia-docker

**Comment by corymast** [comment]
Hi James - I did not have Nvidia-docker installed, thank you for pointing me there. Once I installed Nvidia-docker and ran the above docker run command string, I received the following error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: system has unsupported display driver / cuda driver combination\\\\n\\\"\"": unknown.

I do have an NVIDIA graphics card, although a bit outdated:
![NVIDIA_Driver](https://user-images.githubusercontent.com/31120703/76421706-b2c21080-6369-11ea-8642-fd904c6c6815.png)

I may be able to spin up eight V100 GPUs using MS Azure (I don't have access to DGX-1) however I am a bit unfamiliar with that process and will take some time to accomplish.

Would it be possible to for you to share your model engine file? I would like to train my own model but I would also like to get the redaction application running.

I appreciate all your help!

-Cory

**Comment by james-nvidia** [comment]
I don't know if nvidia-docker is supported on consumer cards like GeForce. This will definitely work on V100s from Azure or any other DGX provider.
We can't share our model file, due to licensing of the dataset, but we can definitely help you train your own model.

I'll close this for now. Please open an issue if you are having issues with the V100s on the cloud.
