### ISSUE TITLE
TX2 capabilities

### ISSUE THREAD

**Issue by lovexytoo** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#9]
Can this project run on tx2? 

I compiled the project according to the [tutorial](https://devblogs.nvidia.com/real-time-redaction-app-nvidia-deepstream-part-2-deployment/),
but when I run 
`./deepstream-redaction-app -c configs/test_source1_fp16.txt`
it ends with errors
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

I have modified sm architecture capabilities to sm_62, is there anything else i should do?

**Comment by james-nvidia** [comment]
Can you follow this issue and let me know if it works?
https://github.com/NVIDIA/retinanet-examples/issues/109#issuecomment-572140450

Thanks
